#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 12 15:59:15 2022

@author: wojciech
"""


import requests
from sys import argv



API_KEY= ''

URL='https://newsapi.org/v2/top-headlines?'

def get_articles_by_category(country, category):
    query_parameters = {
        "category": category,
        "sortBy": "top",
        "country": country,
        "apiKey": API_KEY
    }
    return _get_articles(query_parameters)

def get_articles_by_query(country, query):
    query_parameters = {
        "q": query,
        "sortBy": "top",
        "country": country,
        "apiKey": API_KEY
    }
    return _get_articles(query_parameters)

def _get_articles(params):
    response = requests.get(URL, params=params)

    articles = response.json()['articles']

    results = []
        
    for article in articles:
        results.append({"title": article["title"], "url": article["url"]})

    for result in results:
        print(result['title'])
        print(result['url'])
        print('')

def get_sources_by_category(category):
    url = 'https://newsapi.org/v2/top-headlines/sources'
    query_parameters = {
        "category": category,
        "language": "en",
        "apiKey": API_KEY
    }

    response = requests.get(url, params=query_parameters)

    sources = response.json()['sources']

    for source in sources:
        print(source['name'])
        print(source['url'])

if __name__ == "__main__":
    if len(argv) < 3:
        print("Error: Please specify a country and category")
        exit(1)

    country = argv[1]
    category = argv[2]

    print(f"Getting news for {category} in {country}...\n")
    get_articles_by_category(country,category)
    print(f"Successfully retrieved top {category} headlines in {country}")
